// <auto-generated />
using System;
using AssetManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Data.Data.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    [Migration("20240625081600_UsersSeedData")]
    partial class UsersSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastUpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StaffCode")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7308586-7097-445e-936c-2473da75f698"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04cc5e78-ea78-4b06-8fb8-a13697bcea46",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 756, DateTimeKind.Utc).AddTicks(7532),
                            DateOfBirth = new DateTime(2004, 3, 14, 15, 15, 57, 756, DateTimeKind.Local).AddTicks(7485),
                            Email = "adminhn@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 57, 756, DateTimeKind.Local).AddTicks(7531),
                            LastName = "HN",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 756, DateTimeKind.Utc).AddTicks(7534),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMINHN@GMAIL.COM",
                            NormalizedUserName = "ADMINHN",
                            PasswordHash = "AQAAAAIAAYagAAAAELQQ8Bubyd7EE1LqwLeR0YUBIXNSOvm73Zr4nFnV9rsh+11NqAF6XsrwKio10PZL6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1cac04a-d577-46c0-9852-2f51e35442fc",
                            StaffCode = "SD0002",
                            TwoFactorEnabled = false,
                            UserName = "adminhn"
                        },
                        new
                        {
                            Id = new Guid("fe98eb7a-32d6-4c28-95cd-07ec73f3865a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbe47558-72e9-484c-a399-6b2637825f81",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 693, DateTimeKind.Utc).AddTicks(8919),
                            DateOfBirth = new DateTime(1998, 11, 10, 15, 15, 57, 693, DateTimeKind.Local).AddTicks(8906),
                            Email = "adminhcm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 57, 693, DateTimeKind.Local).AddTicks(8918),
                            LastName = "HCM",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 693, DateTimeKind.Utc).AddTicks(8919),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMINHCM@GMAIL.COM",
                            NormalizedUserName = "ADMINHCM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJKu6aDsOrq+jGa9LJlW4nwNx57V67orCWT/7QqUseod7l2OJpXuKl2zh5TIW0hisQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4bb062a-1d18-442c-af7e-233a5514049e",
                            StaffCode = "SD0001",
                            TwoFactorEnabled = false,
                            UserName = "adminhcm"
                        },
                        new
                        {
                            Id = new Guid("42a87121-a807-4d84-9022-3ea002a7b2d8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7fa25d46-7bb0-4fc3-9dbd-6aa4ab391689",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 886, DateTimeKind.Utc).AddTicks(4027),
                            DateOfBirth = new DateTime(2003, 10, 11, 15, 15, 57, 886, DateTimeKind.Local).AddTicks(3990),
                            Email = "staffhn@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Staff",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 57, 886, DateTimeKind.Local).AddTicks(4026),
                            LastName = "HN",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 886, DateTimeKind.Utc).AddTicks(4028),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "STAFFHN@GMAIL.COM",
                            NormalizedUserName = "STAFFHN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOt0Zu7dCAWLdnFs3Z35diYj4/7a4jXtfhQ4C9fMhR6i1JVjofRNlnfVf0YpJl9jlQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1fd087df-eb8d-4c95-9e12-75664d8d7424",
                            StaffCode = "SD0004",
                            TwoFactorEnabled = false,
                            UserName = "staffhn"
                        },
                        new
                        {
                            Id = new Guid("51bcbbac-c187-408d-ae7a-3d66e0174dc7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e083b0e2-978d-47a4-b3bd-559c5c1958ec",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 821, DateTimeKind.Utc).AddTicks(5774),
                            DateOfBirth = new DateTime(1997, 6, 5, 15, 15, 57, 821, DateTimeKind.Local).AddTicks(5717),
                            Email = "staffhcm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Staff",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 57, 821, DateTimeKind.Local).AddTicks(5772),
                            LastName = "HCM",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 821, DateTimeKind.Utc).AddTicks(5774),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "STAFFHCM@GMAIL.COM",
                            NormalizedUserName = "STAFFHCM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGAD3tJpHEe2mNJseHSpSvPkI27FGOHNhC8UPVDDLabFvGXXpoynr/zXBqlwWeDw6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2cbbe6a-02a7-4e9c-8e9f-4378f7e7745f",
                            StaffCode = "SD0003",
                            TwoFactorEnabled = false,
                            UserName = "staffhcm"
                        },
                        new
                        {
                            Id = new Guid("da88aa77-1ea6-4058-91f8-6d304f6ca14f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f913b14c-c30f-485f-8da3-4a7dd093785b",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 946, DateTimeKind.Utc).AddTicks(8861),
                            DateOfBirth = new DateTime(2006, 4, 24, 15, 15, 57, 946, DateTimeKind.Local).AddTicks(8806),
                            Email = "davida@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "David",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 57, 946, DateTimeKind.Local).AddTicks(8856),
                            LastName = "Anderson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 57, 946, DateTimeKind.Utc).AddTicks(8861),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "DAVIDA@GMAIL.COM",
                            NormalizedUserName = "DAVIDA",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFyJ2dm7BdVbi8WvJw5O7cisHrKWTXc1R+q7zt/LL2ew8M2OpgN5AXz8HQs5Bm2rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f9aa72e6-63b4-4ff6-bf51-4da4fd025c33",
                            StaffCode = "SD0005",
                            TwoFactorEnabled = false,
                            UserName = "davida"
                        },
                        new
                        {
                            Id = new Guid("a5293db5-1b29-4db3-a754-20c97a4b5ebf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61da2c75-9078-497d-a671-b45e466abcd9",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 8, DateTimeKind.Utc).AddTicks(6908),
                            DateOfBirth = new DateTime(1999, 2, 14, 15, 15, 58, 8, DateTimeKind.Local).AddTicks(6847),
                            Email = "harperl@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Harper",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 8, DateTimeKind.Local).AddTicks(6907),
                            LastName = "Lewis",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 8, DateTimeKind.Utc).AddTicks(6908),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "HARPERL@GMAIL.COM",
                            NormalizedUserName = "HARPERL",
                            PasswordHash = "AQAAAAIAAYagAAAAEMmJYgq7DEvwvIdk5D/8l/S/kepJymcRr7n5KzdfbYc58EvVtmY6KOrbr+hi5GajCg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "53599593-7bee-4179-8cbc-9dc241a8e8ef",
                            StaffCode = "SD0006",
                            TwoFactorEnabled = false,
                            UserName = "harperl"
                        },
                        new
                        {
                            Id = new Guid("057c7eee-c467-436a-abd8-fe8dcb099fad"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "935c1327-75b5-4fd3-9a14-e3308165d4ee",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 69, DateTimeKind.Utc).AddTicks(9045),
                            DateOfBirth = new DateTime(1996, 1, 3, 15, 15, 58, 69, DateTimeKind.Local).AddTicks(9017),
                            Email = "emmaw@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Emma",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 69, DateTimeKind.Local).AddTicks(9044),
                            LastName = "Wilson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 69, DateTimeKind.Utc).AddTicks(9045),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "EMMAW@GMAIL.COM",
                            NormalizedUserName = "EMMAW",
                            PasswordHash = "AQAAAAIAAYagAAAAEGAGXnndkJZPZgdMjD6mWwpXC0AY1LzrPDlWOPbMDXUiC3/MCBPe9K5PYgntUOcusQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "787189c9-83d5-4ad1-aeae-3bca9fd73596",
                            StaffCode = "SD0007",
                            TwoFactorEnabled = false,
                            UserName = "emmaw"
                        },
                        new
                        {
                            Id = new Guid("8ebc0ca4-bd69-478f-b049-ea9f2dcf9358"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96a459ab-f970-4f18-adbf-f3b4c488c459",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 134, DateTimeKind.Utc).AddTicks(4111),
                            DateOfBirth = new DateTime(1999, 6, 30, 15, 15, 58, 134, DateTimeKind.Local).AddTicks(4080),
                            Email = "michaelj@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Michael",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 134, DateTimeKind.Local).AddTicks(4110),
                            LastName = "Johnson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 134, DateTimeKind.Utc).AddTicks(4112),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "MICHAELJ@GMAIL.COM",
                            NormalizedUserName = "MICHAELJ",
                            PasswordHash = "AQAAAAIAAYagAAAAELRgJM04ByjYtCWKcPtULE6cVZit179Fkt0JoMmtqrMwhQ/ZeFH0RQeKXKzopWxO7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "71d26bcf-ff29-4da0-96b1-cfef580e2bdd",
                            StaffCode = "SD0008",
                            TwoFactorEnabled = false,
                            UserName = "michaelj"
                        },
                        new
                        {
                            Id = new Guid("b0128f5b-00a2-4220-9512-73b08c838476"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "736c48f1-d46d-4fef-86d8-99c4612197b2",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 218, DateTimeKind.Utc).AddTicks(2682),
                            DateOfBirth = new DateTime(2002, 9, 10, 15, 15, 58, 218, DateTimeKind.Local).AddTicks(2645),
                            Email = "evelynw@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Evelyn",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 218, DateTimeKind.Local).AddTicks(2681),
                            LastName = "Williams",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 218, DateTimeKind.Utc).AddTicks(2683),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "EVELYNW@GMAIL.COM",
                            NormalizedUserName = "EVELYNW",
                            PasswordHash = "AQAAAAIAAYagAAAAEFOVjPcmLovTlnVtHDk+fU7ofaX+aG06wGTvRug+mwiqsu2Pu9cA11BXOP1BNRQzlQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfce9434-f293-4fb2-8e8b-0b5e1580cce3",
                            StaffCode = "SD0009",
                            TwoFactorEnabled = false,
                            UserName = "evelynw"
                        },
                        new
                        {
                            Id = new Guid("496b1e47-5954-4c4a-9c85-80d26c53900d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a9fb8033-674f-44c0-88d8-d2892817af68",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 281, DateTimeKind.Utc).AddTicks(7668),
                            DateOfBirth = new DateTime(2003, 2, 18, 15, 15, 58, 281, DateTimeKind.Local).AddTicks(7648),
                            Email = "harperm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Harper",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 281, DateTimeKind.Local).AddTicks(7666),
                            LastName = "Martinez",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 281, DateTimeKind.Utc).AddTicks(7668),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "HARPERM@GMAIL.COM",
                            NormalizedUserName = "HARPERM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGJORVuNEsm/vEdrZEyYcmt3ejnNPlUXj4SSkF2CbxuP9SCV+jhSdeGwOUpeOgWWxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db21b1d1-7964-48d1-a38b-0f1b0d3445a8",
                            StaffCode = "SD0010",
                            TwoFactorEnabled = false,
                            UserName = "harperm"
                        },
                        new
                        {
                            Id = new Guid("119809f5-f4da-4b1b-83e1-5e06b475f3cc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c5d770e-135d-4def-9776-e43ef2f7ac17",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 340, DateTimeKind.Utc).AddTicks(2226),
                            DateOfBirth = new DateTime(1997, 6, 11, 15, 15, 58, 340, DateTimeKind.Local).AddTicks(2207),
                            Email = "ameliat@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Amelia",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 340, DateTimeKind.Local).AddTicks(2224),
                            LastName = "Thomas",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 340, DateTimeKind.Utc).AddTicks(2226),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "AMELIAT@GMAIL.COM",
                            NormalizedUserName = "AMELIAT",
                            PasswordHash = "AQAAAAIAAYagAAAAEMUw7wLIShOGh6r7vP9OlMs9lqu48A77/Mm09Gqh+2U8xJ7zNhd87JGrkt3UMRxU7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9244b497-300d-49d6-8e91-ba47dc4ac2d5",
                            StaffCode = "SD0011",
                            TwoFactorEnabled = false,
                            UserName = "ameliat"
                        },
                        new
                        {
                            Id = new Guid("0d7ff7cc-9a44-43fb-96c6-aa0adb0fa897"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2a495255-d406-4ecc-a0c5-3b0abdc91aeb",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 401, DateTimeKind.Utc).AddTicks(7889),
                            DateOfBirth = new DateTime(2004, 6, 7, 15, 15, 58, 401, DateTimeKind.Local).AddTicks(7871),
                            Email = "daniell@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Daniel",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 401, DateTimeKind.Local).AddTicks(7887),
                            LastName = "Lewis",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 401, DateTimeKind.Utc).AddTicks(7890),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "DANIELL@GMAIL.COM",
                            NormalizedUserName = "DANIELL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJJCOlpVkBhV2YoPGZQ0y71KuFqtrLJFizIRO/KpGJMu1d0g0zYUlwbb9SD3wRsUEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5be713d-f8a8-43b6-91da-d005126559a7",
                            StaffCode = "SD0012",
                            TwoFactorEnabled = false,
                            UserName = "daniell"
                        },
                        new
                        {
                            Id = new Guid("6f56a37f-aaa0-49cc-ae7d-1465528d0a55"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd7592cf-c984-49de-91d5-f5fb1565bb51",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 467, DateTimeKind.Utc).AddTicks(1059),
                            DateOfBirth = new DateTime(2006, 1, 26, 15, 15, 58, 467, DateTimeKind.Local).AddTicks(1043),
                            Email = "oliviah@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Olivia",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 467, DateTimeKind.Local).AddTicks(1058),
                            LastName = "Harris",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 467, DateTimeKind.Utc).AddTicks(1060),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "OLIVIAH@GMAIL.COM",
                            NormalizedUserName = "OLIVIAH",
                            PasswordHash = "AQAAAAIAAYagAAAAELwYyjFvLF2w7mQh8HFtml/WK5O3/9yKUQNXdFgfuTmDi1t26qWEAIfBUJgRAtFMmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e948871-ba5d-41ef-841f-cea156d05345",
                            StaffCode = "SD0013",
                            TwoFactorEnabled = false,
                            UserName = "oliviah"
                        },
                        new
                        {
                            Id = new Guid("b20939f3-fe91-4786-9d5f-dbef3dc7b69d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab63fda1-0e5f-4231-a53c-ae37361a1fc2",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 528, DateTimeKind.Utc).AddTicks(2780),
                            DateOfBirth = new DateTime(2003, 1, 18, 15, 15, 58, 528, DateTimeKind.Local).AddTicks(2761),
                            Email = "davidj@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "David",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 528, DateTimeKind.Local).AddTicks(2779),
                            LastName = "Johnson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 528, DateTimeKind.Utc).AddTicks(2781),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "DAVIDJ@GMAIL.COM",
                            NormalizedUserName = "DAVIDJ",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ+eHWqoS/CCTXqNP8AbyKDbF7Z9FQPg4eczDPEi2sO02DzCh1rPa3J1dAZKXoTTNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f36c38e9-c577-4994-b717-de174734c221",
                            StaffCode = "SD0014",
                            TwoFactorEnabled = false,
                            UserName = "davidj"
                        },
                        new
                        {
                            Id = new Guid("e0b500f6-332e-4f63-8bd9-a43fe8e690ea"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "91dd7e97-4762-41d8-832e-7c36479a6f90",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 589, DateTimeKind.Utc).AddTicks(4120),
                            DateOfBirth = new DateTime(1995, 8, 28, 15, 15, 58, 589, DateTimeKind.Local).AddTicks(4101),
                            Email = "davidm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "David",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 589, DateTimeKind.Local).AddTicks(4118),
                            LastName = "Martinez",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 589, DateTimeKind.Utc).AddTicks(4121),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "DAVIDM@GMAIL.COM",
                            NormalizedUserName = "DAVIDM",
                            PasswordHash = "AQAAAAIAAYagAAAAEENuUmGW/NVzuyYFlMRq9EnO2qGSCPBxRgFlq9KnSTw1SIcTQFdHnVOMZOewT83ZfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7001e3bd-eb17-43cb-91fb-78b1816bdac2",
                            StaffCode = "SD0015",
                            TwoFactorEnabled = false,
                            UserName = "davidm"
                        },
                        new
                        {
                            Id = new Guid("1803dbcc-6a78-4080-887f-0ef25e57811f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c080cc0a-f939-4038-9f08-9d4371497a83",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 650, DateTimeKind.Utc).AddTicks(5361),
                            DateOfBirth = new DateTime(1997, 3, 11, 15, 15, 58, 650, DateTimeKind.Local).AddTicks(5348),
                            Email = "charlottey@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Charlotte",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 650, DateTimeKind.Local).AddTicks(5360),
                            LastName = "Young",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 650, DateTimeKind.Utc).AddTicks(5362),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "CHARLOTTEY@GMAIL.COM",
                            NormalizedUserName = "CHARLOTTEY",
                            PasswordHash = "AQAAAAIAAYagAAAAEMAobjC9e9S1OycE7aoSb48AOIuZDeIXtPcsDLcLLkTw5b+5PAFL4Y9icx0BEoBySQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94a1f71f-9052-49e6-8069-00d423aa6cdb",
                            StaffCode = "SD0016",
                            TwoFactorEnabled = false,
                            UserName = "charlottey"
                        },
                        new
                        {
                            Id = new Guid("a2297cd4-ff02-4054-85a3-f954fae8f5e6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a30a3484-81fd-4ea2-b04d-c6094bab7e8a",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 710, DateTimeKind.Utc).AddTicks(6000),
                            DateOfBirth = new DateTime(2004, 9, 23, 15, 15, 58, 710, DateTimeKind.Local).AddTicks(5983),
                            Email = "danielm1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Daniel",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 710, DateTimeKind.Local).AddTicks(5999),
                            LastName = "Martinez",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 710, DateTimeKind.Utc).AddTicks(6000),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "DANIELM1@GMAIL.COM",
                            NormalizedUserName = "DANIELM1",
                            PasswordHash = "AQAAAAIAAYagAAAAEHwZKm/8eaMAk+54qBZxXt5DPOwmciuKLRbzTp+Gp9VKjwfs4a8tBBGLEZFSvnvD2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a27c4a47-5f95-419c-953a-122e1da910c3",
                            StaffCode = "SD0017",
                            TwoFactorEnabled = false,
                            UserName = "danielm1"
                        },
                        new
                        {
                            Id = new Guid("2ff30446-27c5-44ff-85b4-c7cde3442a5a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b188869-4d40-47a7-8ee9-810fa8130515",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 771, DateTimeKind.Utc).AddTicks(2030),
                            DateOfBirth = new DateTime(2005, 6, 22, 15, 15, 58, 771, DateTimeKind.Local).AddTicks(2018),
                            Email = "danielj@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Daniel",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 771, DateTimeKind.Local).AddTicks(2029),
                            LastName = "Jackson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 771, DateTimeKind.Utc).AddTicks(2030),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "DANIELJ@GMAIL.COM",
                            NormalizedUserName = "DANIELJ",
                            PasswordHash = "AQAAAAIAAYagAAAAEFGOI5T/tNIyBj4lOjL90cnhgRD4dt27lvkYiYBKCsRMMzcU0nb1X0BVcuFudHWIHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f40d5140-e7d4-40a7-b769-52361ce1a999",
                            StaffCode = "SD0018",
                            TwoFactorEnabled = false,
                            UserName = "danielj"
                        },
                        new
                        {
                            Id = new Guid("4f6683f1-46ad-4226-907a-7e9c6dc38d09"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2127d44-df90-4d66-a8cc-57413175875f",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 832, DateTimeKind.Utc).AddTicks(4019),
                            DateOfBirth = new DateTime(2005, 5, 29, 15, 15, 58, 832, DateTimeKind.Local).AddTicks(4004),
                            Email = "michaelc@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Michael",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 832, DateTimeKind.Local).AddTicks(4017),
                            LastName = "Clark",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 832, DateTimeKind.Utc).AddTicks(4019),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "MICHAELC@GMAIL.COM",
                            NormalizedUserName = "MICHAELC",
                            PasswordHash = "AQAAAAIAAYagAAAAEOQD4VA4A/zioXlER0tL7BMDpqSujx26tWShQKDYm5NvqK8FC3nPb2LVoYtT9w9MtA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4188a0e9-d1dd-4cd0-84b2-c4b41315f71a",
                            StaffCode = "SD0019",
                            TwoFactorEnabled = false,
                            UserName = "michaelc"
                        },
                        new
                        {
                            Id = new Guid("769e20c2-20b1-41aa-be53-c7f3ee380256"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8e47364-b6da-40a1-96b3-247e0d5ef4ed",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 894, DateTimeKind.Utc).AddTicks(891),
                            DateOfBirth = new DateTime(1998, 12, 17, 15, 15, 58, 894, DateTimeKind.Local).AddTicks(866),
                            Email = "harperj1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Harper",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 894, DateTimeKind.Local).AddTicks(890),
                            LastName = "Jackson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 894, DateTimeKind.Utc).AddTicks(892),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "HARPERJ1@GMAIL.COM",
                            NormalizedUserName = "HARPERJ1",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzAPZ65uYuyyHdBgFQUN32EQkFKjzIZodSdAe0ILUCuu7EFKk+PsAC+cOTkYSvA1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e0a9980d-72bb-4ebd-a5b1-3bdd1c02c05f",
                            StaffCode = "SD0020",
                            TwoFactorEnabled = false,
                            UserName = "harperj1"
                        },
                        new
                        {
                            Id = new Guid("f1e6e929-b2d4-490b-bb56-d266b4578a6b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7131bff-c101-4891-9ce6-0b37d0bd2c92",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 955, DateTimeKind.Utc).AddTicks(3683),
                            DateOfBirth = new DateTime(2005, 2, 11, 15, 15, 58, 955, DateTimeKind.Local).AddTicks(3670),
                            Email = "olivial@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Olivia",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 58, 955, DateTimeKind.Local).AddTicks(3682),
                            LastName = "Lewis",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 58, 955, DateTimeKind.Utc).AddTicks(3684),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "OLIVIAL@GMAIL.COM",
                            NormalizedUserName = "OLIVIAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzt96TSUuyGhrT+NzDDNcS4fCmkopibq56l6Ec6APIGLo7Fr8mRLjQ8mYdc5+zaSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9058a16-f9d8-47cc-b883-7a0bc68f75c7",
                            StaffCode = "SD0021",
                            TwoFactorEnabled = false,
                            UserName = "olivial"
                        },
                        new
                        {
                            Id = new Guid("ea657ee0-892a-4394-ae44-9c88aed2d097"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "23618426-bfce-4bf5-988d-bc0cf50d500c",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 15, DateTimeKind.Utc).AddTicks(9202),
                            DateOfBirth = new DateTime(1998, 12, 18, 15, 15, 59, 15, DateTimeKind.Local).AddTicks(9196),
                            Email = "avay@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ava",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 15, DateTimeKind.Local).AddTicks(9201),
                            LastName = "Young",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 15, DateTimeKind.Utc).AddTicks(9203),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "AVAY@GMAIL.COM",
                            NormalizedUserName = "AVAY",
                            PasswordHash = "AQAAAAIAAYagAAAAECFO0BkGdLa8DXDGcmapBOH17dxSWsCikjIm5Z7qjSkxJGltVuDugHXkv6ZlnlJKKA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c798c48-0eb6-48d2-b455-2dec8abb6650",
                            StaffCode = "SD0022",
                            TwoFactorEnabled = false,
                            UserName = "avay"
                        },
                        new
                        {
                            Id = new Guid("c986abab-32d7-4112-bf7a-e9a6dfeb8eb4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01c31d59-36c6-434d-b5b7-6461654a0275",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 76, DateTimeKind.Utc).AddTicks(7639),
                            DateOfBirth = new DateTime(2006, 1, 19, 15, 15, 59, 76, DateTimeKind.Local).AddTicks(7621),
                            Email = "josephm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Joseph",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 76, DateTimeKind.Local).AddTicks(7637),
                            LastName = "Martinez",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 76, DateTimeKind.Utc).AddTicks(7639),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "JOSEPHM@GMAIL.COM",
                            NormalizedUserName = "JOSEPHM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJPbAssWjjEnkcuw+RIVLifWF9SazYnRRMRub/Ni9X9mFoSlfFnyt+hFG7JO/oSI0g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47519493-13d2-4763-a201-9a844bdd610b",
                            StaffCode = "SD0023",
                            TwoFactorEnabled = false,
                            UserName = "josephm"
                        },
                        new
                        {
                            Id = new Guid("88b2652e-59e8-41f9-b5a1-3a4d68934c97"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3194e159-2125-4814-8041-8c3444157f4d",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 137, DateTimeKind.Utc).AddTicks(8995),
                            DateOfBirth = new DateTime(2000, 9, 8, 15, 15, 59, 137, DateTimeKind.Local).AddTicks(8969),
                            Email = "avaj@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ava",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 137, DateTimeKind.Local).AddTicks(8993),
                            LastName = "Jones",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 137, DateTimeKind.Utc).AddTicks(8996),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "AVAJ@GMAIL.COM",
                            NormalizedUserName = "AVAJ",
                            PasswordHash = "AQAAAAIAAYagAAAAEKn0vdKteYJpWdzra9C4ioLhc4uY8WkYcso/nR/ZyJCMw/6JN1f6Jrk2bUbI0qydAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f312f56-9d31-43a7-867a-d4c94002cc3f",
                            StaffCode = "SD0024",
                            TwoFactorEnabled = false,
                            UserName = "avaj"
                        },
                        new
                        {
                            Id = new Guid("2af6972d-353c-424d-8fce-858736057342"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a46d4f62-6425-42b6-9a89-238ee4bf5e02",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 200, DateTimeKind.Utc).AddTicks(449),
                            DateOfBirth = new DateTime(1996, 10, 10, 15, 15, 59, 200, DateTimeKind.Local).AddTicks(335),
                            Email = "alexanderm@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Alexander",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 200, DateTimeKind.Local).AddTicks(448),
                            LastName = "Miller",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 200, DateTimeKind.Utc).AddTicks(450),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ALEXANDERM@GMAIL.COM",
                            NormalizedUserName = "ALEXANDERM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKp7GRfKY+sly1knAlxVFgM9nOAwzU1naYpiYeieoEak4vg7AdkgYIF2g3c7lryxEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a86dfa6f-7d67-4060-aa9c-676f8f5cb3cd",
                            StaffCode = "SD0025",
                            TwoFactorEnabled = false,
                            UserName = "alexanderm"
                        },
                        new
                        {
                            Id = new Guid("b9c2a766-b7f2-4e97-8804-d6e0a3a0d93b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ed543b8-95ca-4126-bad2-5d90495183b6",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 262, DateTimeKind.Utc).AddTicks(1176),
                            DateOfBirth = new DateTime(2002, 7, 25, 15, 15, 59, 262, DateTimeKind.Local).AddTicks(1160),
                            Email = "benjamind@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Benjamin",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 262, DateTimeKind.Local).AddTicks(1175),
                            LastName = "Davis",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 262, DateTimeKind.Utc).AddTicks(1177),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "BENJAMIND@GMAIL.COM",
                            NormalizedUserName = "BENJAMIND",
                            PasswordHash = "AQAAAAIAAYagAAAAEDkMLmUjgHDz1HIuvpBmLRITD8OWNHHE7+SLtE1CPuVVaN/EC+0G+aKn6om5ypPvpA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02797f16-6073-421b-ae10-cb80f36332da",
                            StaffCode = "SD0026",
                            TwoFactorEnabled = false,
                            UserName = "benjamind"
                        },
                        new
                        {
                            Id = new Guid("1d10808f-d13e-47c8-93ab-9e3fa5d0902b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44bf8bd8-d37e-4625-8691-88e6a20fd443",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 325, DateTimeKind.Utc).AddTicks(7701),
                            DateOfBirth = new DateTime(1998, 7, 2, 15, 15, 59, 325, DateTimeKind.Local).AddTicks(7681),
                            Email = "harperr@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Harper",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 325, DateTimeKind.Local).AddTicks(7700),
                            LastName = "Rodriguez",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 325, DateTimeKind.Utc).AddTicks(7702),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "HARPERR@GMAIL.COM",
                            NormalizedUserName = "HARPERR",
                            PasswordHash = "AQAAAAIAAYagAAAAELQy3HddWCqE3phgm30D0eDXIyvzxw9kjltpp6BMhSYzcTSKHzKEIkmelhzO8whOrg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d61d450-ac0a-491d-baf1-d9971e841ee2",
                            StaffCode = "SD0027",
                            TwoFactorEnabled = false,
                            UserName = "harperr"
                        },
                        new
                        {
                            Id = new Guid("16c7753c-e27c-4c48-925f-7d77ef8f5492"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66add950-2765-4554-a7a2-ee837e2199fa",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 386, DateTimeKind.Utc).AddTicks(2544),
                            DateOfBirth = new DateTime(2004, 12, 30, 15, 15, 59, 386, DateTimeKind.Local).AddTicks(2517),
                            Email = "elijaht@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Elijah",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 386, DateTimeKind.Local).AddTicks(2542),
                            LastName = "Thomas",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 386, DateTimeKind.Utc).AddTicks(2544),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ELIJAHT@GMAIL.COM",
                            NormalizedUserName = "ELIJAHT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbWEGgAD+mBg1yZf9ICMbQO1+arIyYHF8kzDrDKAJ/NjoTtFOiZS8AlMTc2S9MJ4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8b5794b-bf1a-4c6b-aaa5-328f70e9d2f2",
                            StaffCode = "SD0028",
                            TwoFactorEnabled = false,
                            UserName = "elijaht"
                        },
                        new
                        {
                            Id = new Guid("6d948de7-b0a6-45bd-9ac3-b5ed1c81cdad"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1ebed4f-e42f-41ac-a0ca-36afc9e553c3",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 449, DateTimeKind.Utc).AddTicks(2233),
                            DateOfBirth = new DateTime(2004, 5, 19, 15, 15, 59, 449, DateTimeKind.Local).AddTicks(2211),
                            Email = "isabellah@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Isabella",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 449, DateTimeKind.Local).AddTicks(2232),
                            LastName = "Harris",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 449, DateTimeKind.Utc).AddTicks(2234),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ISABELLAH@GMAIL.COM",
                            NormalizedUserName = "ISABELLAH",
                            PasswordHash = "AQAAAAIAAYagAAAAELpeK8EKFhKx08I9wpOFdY1s038hU81D+lUztJdOwJl1OEpxV+o/X4Qvhn4YabPdEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b51953df-0edd-4820-93ea-56607fcf52e7",
                            StaffCode = "SD0029",
                            TwoFactorEnabled = false,
                            UserName = "isabellah"
                        },
                        new
                        {
                            Id = new Guid("764dd036-756f-41b4-bf84-65222d64c76f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "91f58775-2081-43f0-b881-091a9d6a55db",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 513, DateTimeKind.Utc).AddTicks(6394),
                            DateOfBirth = new DateTime(2001, 2, 4, 15, 15, 59, 513, DateTimeKind.Local).AddTicks(6363),
                            Email = "emmat@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Emma",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 513, DateTimeKind.Local).AddTicks(6392),
                            LastName = "Taylor",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 513, DateTimeKind.Utc).AddTicks(6394),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "EMMAT@GMAIL.COM",
                            NormalizedUserName = "EMMAT",
                            PasswordHash = "AQAAAAIAAYagAAAAEOPifAV0tqyT2dkPNP0gkXHbjyCJNtaqsoubN1Jp76TP2TiV7S3GWJHHTyB+bZe+Ng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d8bf67fd-4623-4903-8f09-e1fefdefb014",
                            StaffCode = "SD0030",
                            TwoFactorEnabled = false,
                            UserName = "emmat"
                        },
                        new
                        {
                            Id = new Guid("6bb9f598-0dfc-4ca4-af61-866cc25238f7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "304bb28f-f043-4dc5-bf40-3604f6e1eecb",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 575, DateTimeKind.Utc).AddTicks(6891),
                            DateOfBirth = new DateTime(2006, 4, 2, 15, 15, 59, 575, DateTimeKind.Local).AddTicks(6875),
                            Email = "oliviaj1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Olivia",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 575, DateTimeKind.Local).AddTicks(6889),
                            LastName = "Jackson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 575, DateTimeKind.Utc).AddTicks(6891),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "OLIVIAJ1@GMAIL.COM",
                            NormalizedUserName = "OLIVIAJ1",
                            PasswordHash = "AQAAAAIAAYagAAAAEHZ646+/tkj3ObOIZxhj+skiT1Wee41DiImkv76XzyyvWfGP6Y8vMiiW1SuW298AzQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f067050-b858-407d-b365-60702c43298b",
                            StaffCode = "SD0031",
                            TwoFactorEnabled = false,
                            UserName = "oliviaj1"
                        },
                        new
                        {
                            Id = new Guid("ad2bc3e9-64d4-45af-8e5d-e0bd598dc218"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b288851f-da20-40cb-beae-f4889fbbdf4c",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 636, DateTimeKind.Utc).AddTicks(5528),
                            DateOfBirth = new DateTime(2005, 10, 11, 15, 15, 59, 636, DateTimeKind.Local).AddTicks(5515),
                            Email = "elijahw@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Elijah",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 636, DateTimeKind.Local).AddTicks(5527),
                            LastName = "Williams",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 636, DateTimeKind.Utc).AddTicks(5529),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "ELIJAHW@GMAIL.COM",
                            NormalizedUserName = "ELIJAHW",
                            PasswordHash = "AQAAAAIAAYagAAAAEPryjVJxOTKQ0wnSH9pnJR2YiLSCym5vWJLlCr5zBIyYVt1Fez+w6fb3iEQhS11AbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3755d092-9572-4f79-9b43-46557d9290e9",
                            StaffCode = "SD0032",
                            TwoFactorEnabled = false,
                            UserName = "elijahw"
                        },
                        new
                        {
                            Id = new Guid("5d983e82-fde8-45c1-9862-374566598c83"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31c9ec2a-65b9-4202-8167-a717311d2db5",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 698, DateTimeKind.Utc).AddTicks(6507),
                            DateOfBirth = new DateTime(2005, 12, 31, 15, 15, 59, 698, DateTimeKind.Local).AddTicks(6486),
                            Email = "alexanderm1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Alexander",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 698, DateTimeKind.Local).AddTicks(6506),
                            LastName = "Miller",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 698, DateTimeKind.Utc).AddTicks(6508),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ALEXANDERM1@GMAIL.COM",
                            NormalizedUserName = "ALEXANDERM1",
                            PasswordHash = "AQAAAAIAAYagAAAAEON3Ipyd2wQGHjnzNZg6d4bWZwrrAXkiKEg6l5lA1RyWvrlvgEACJnKFUbHTljQgeA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15fd9388-43ab-4d7c-9f02-e25f90eb6a1a",
                            StaffCode = "SD0033",
                            TwoFactorEnabled = false,
                            UserName = "alexanderm1"
                        },
                        new
                        {
                            Id = new Guid("528f86cd-75b8-4692-981d-c6e29d5c0882"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9978bbf-e6ff-44c5-bb64-948a4b81117f",
                            CreatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 760, DateTimeKind.Utc).AddTicks(3201),
                            DateOfBirth = new DateTime(1995, 6, 19, 15, 15, 59, 760, DateTimeKind.Local).AddTicks(3174),
                            Email = "isabellaj2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Isabella",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = false,
                            JoinedDate = new DateTime(2024, 6, 25, 15, 15, 59, 760, DateTimeKind.Local).AddTicks(3200),
                            LastName = "Jackson",
                            LastUpdatedDateTime = new DateTime(2024, 6, 25, 8, 15, 59, 760, DateTimeKind.Utc).AddTicks(3201),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ISABELLAJ2@GMAIL.COM",
                            NormalizedUserName = "ISABELLAJ2",
                            PasswordHash = "AQAAAAIAAYagAAAAECZDwNVwdxjRK4Qot6a6mZFw6M4C4xtXynSwtJx9S5vXGToz7+/hg1sm351A0lGA7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2be7a5cb-3a96-4640-ac7f-99d679e78644",
                            StaffCode = "SD0034",
                            TwoFactorEnabled = false,
                            UserName = "isabellaj2"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3"),
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c7308586-7097-445e-936c-2473da75f698"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("fe98eb7a-32d6-4c28-95cd-07ec73f3865a"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("42a87121-a807-4d84-9022-3ea002a7b2d8"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("51bcbbac-c187-408d-ae7a-3d66e0174dc7"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("da88aa77-1ea6-4058-91f8-6d304f6ca14f"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("a5293db5-1b29-4db3-a754-20c97a4b5ebf"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("057c7eee-c467-436a-abd8-fe8dcb099fad"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("8ebc0ca4-bd69-478f-b049-ea9f2dcf9358"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("b0128f5b-00a2-4220-9512-73b08c838476"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("496b1e47-5954-4c4a-9c85-80d26c53900d"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("119809f5-f4da-4b1b-83e1-5e06b475f3cc"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("0d7ff7cc-9a44-43fb-96c6-aa0adb0fa897"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("6f56a37f-aaa0-49cc-ae7d-1465528d0a55"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("b20939f3-fe91-4786-9d5f-dbef3dc7b69d"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("e0b500f6-332e-4f63-8bd9-a43fe8e690ea"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("1803dbcc-6a78-4080-887f-0ef25e57811f"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("a2297cd4-ff02-4054-85a3-f954fae8f5e6"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("2ff30446-27c5-44ff-85b4-c7cde3442a5a"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("4f6683f1-46ad-4226-907a-7e9c6dc38d09"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("769e20c2-20b1-41aa-be53-c7f3ee380256"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("f1e6e929-b2d4-490b-bb56-d266b4578a6b"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("ea657ee0-892a-4394-ae44-9c88aed2d097"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("c986abab-32d7-4112-bf7a-e9a6dfeb8eb4"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("88b2652e-59e8-41f9-b5a1-3a4d68934c97"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("2af6972d-353c-424d-8fce-858736057342"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("b9c2a766-b7f2-4e97-8804-d6e0a3a0d93b"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("1d10808f-d13e-47c8-93ab-9e3fa5d0902b"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("16c7753c-e27c-4c48-925f-7d77ef8f5492"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("6d948de7-b0a6-45bd-9ac3-b5ed1c81cdad"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("764dd036-756f-41b4-bf84-65222d64c76f"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("6bb9f598-0dfc-4ca4-af61-866cc25238f7"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("ad2bc3e9-64d4-45af-8e5d-e0bd598dc218"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("5d983e82-fde8-45c1-9862-374566598c83"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("528f86cd-75b8-4692-981d-c6e29d5c0882"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
