// <auto-generated />
using System;
using AssetManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Data.Data.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    partial class AssetManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastUpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StaffCode")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe4d7e10-e60c-445a-8c6c-a00edc97e42f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ca9cf31-6b0b-4295-be51-a10654d38049",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 699, DateTimeKind.Utc).AddTicks(3448),
                            DateOfBirth = new DateTime(2005, 5, 20, 11, 30, 15, 699, DateTimeKind.Local).AddTicks(3442),
                            Email = "admin2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst2",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 15, 699, DateTimeKind.Local).AddTicks(3447),
                            LastName = "AdminLast2",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 699, DateTimeKind.Utc).AddTicks(3448),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN2@GMAIL.COM",
                            NormalizedUserName = "ADMIN2",
                            PasswordHash = "AQAAAAIAAYagAAAAEMkeIHmevnOM2KAxnKx+wxE1WZZ+MTCynCpsZ7qGdkumaUOyK/Gd02z1m/Z6PaLofw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1ae30c4f-3699-4ceb-9bb9-f384e3a6a9d2",
                            StaffCode = "SD0002",
                            TwoFactorEnabled = false,
                            UserName = "admin2"
                        },
                        new
                        {
                            Id = new Guid("bafc9d75-79bd-4608-abca-7e9931a0d7d4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a322adb-2e91-4bbe-ad3d-949b21ec823d",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 757, DateTimeKind.Utc).AddTicks(5917),
                            DateOfBirth = new DateTime(1997, 3, 3, 11, 30, 15, 757, DateTimeKind.Local).AddTicks(5887),
                            Email = "admin3@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst3",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 15, 757, DateTimeKind.Local).AddTicks(5916),
                            LastName = "AdminLast3",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 757, DateTimeKind.Utc).AddTicks(5918),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN3@GMAIL.COM",
                            NormalizedUserName = "ADMIN3",
                            PasswordHash = "AQAAAAIAAYagAAAAEPIpG73ebvoKLGp+XWR8wz4ZJNNqeET4c+WCqw62UHpVjh7WHkFD2m8gZYUFuA0iSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82db8182-5dd8-49f0-be4e-27fda6d20884",
                            StaffCode = "SD0003",
                            TwoFactorEnabled = false,
                            UserName = "admin3"
                        },
                        new
                        {
                            Id = new Guid("ad9c337a-bb6b-4949-b796-14620afd0f08"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "368ebef8-6228-473c-ae78-c0ebb03b503b",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 816, DateTimeKind.Utc).AddTicks(1436),
                            DateOfBirth = new DateTime(2005, 2, 19, 11, 30, 15, 816, DateTimeKind.Local).AddTicks(1415),
                            Email = "admin4@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst4",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 15, 816, DateTimeKind.Local).AddTicks(1435),
                            LastName = "AdminLast4",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 816, DateTimeKind.Utc).AddTicks(1437),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN4@GMAIL.COM",
                            NormalizedUserName = "ADMIN4",
                            PasswordHash = "AQAAAAIAAYagAAAAEP46NN4DV6Rn5DkA2C+f+lQrOWGzgMCNGRjHK5bZe76nhdbIB8KD1/93Mid95YTM/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "60b16981-bce4-4510-913d-29e8034a6899",
                            StaffCode = "SD0004",
                            TwoFactorEnabled = false,
                            UserName = "admin4"
                        },
                        new
                        {
                            Id = new Guid("94814fe8-b396-4bb5-9f64-e9d91407c831"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14e8bc62-0938-459f-b909-8ac1830395a9",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 874, DateTimeKind.Utc).AddTicks(9095),
                            DateOfBirth = new DateTime(2001, 11, 8, 11, 30, 15, 874, DateTimeKind.Local).AddTicks(9081),
                            Email = "admin5@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst5",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 15, 874, DateTimeKind.Local).AddTicks(9094),
                            LastName = "AdminLast5",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 874, DateTimeKind.Utc).AddTicks(9096),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN5@GMAIL.COM",
                            NormalizedUserName = "ADMIN5",
                            PasswordHash = "AQAAAAIAAYagAAAAEDrrj9HlR0vK5SNQED4tFgsmdCjbyZpXaFxj2Gleqm44S39gmR0Ue8XGo89q7B7wTQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e1e49b57-b2b2-4969-b56f-aedee6c9689d",
                            StaffCode = "SD0005",
                            TwoFactorEnabled = false,
                            UserName = "admin5"
                        },
                        new
                        {
                            Id = new Guid("523b214c-6eac-42f1-96b2-cc1fca0ad2ec"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd04ad99-603d-4836-b23d-bce8269af43e",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 935, DateTimeKind.Utc).AddTicks(1913),
                            DateOfBirth = new DateTime(2000, 10, 31, 11, 30, 15, 935, DateTimeKind.Local).AddTicks(1897),
                            Email = "admin6@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst6",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 15, 935, DateTimeKind.Local).AddTicks(1912),
                            LastName = "AdminLast6",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 935, DateTimeKind.Utc).AddTicks(1913),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN6@GMAIL.COM",
                            NormalizedUserName = "ADMIN6",
                            PasswordHash = "AQAAAAIAAYagAAAAEMqIZ/JWNpwB4lPerwFevheGQwvjITPaSRZlKxUYsq7pGUIx/Lgwau47KKsuiN32Dw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "efe2a8ca-f303-418a-a063-922571b6ee03",
                            StaffCode = "SD0006",
                            TwoFactorEnabled = false,
                            UserName = "admin6"
                        },
                        new
                        {
                            Id = new Guid("e11eb642-3086-4b6f-9ef0-d10460968dd5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1710d17d-f952-4dc9-bfd5-47a5b378a622",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 993, DateTimeKind.Utc).AddTicks(3920),
                            DateOfBirth = new DateTime(2002, 1, 24, 11, 30, 15, 993, DateTimeKind.Local).AddTicks(3905),
                            Email = "admin7@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst7",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 15, 993, DateTimeKind.Local).AddTicks(3919),
                            LastName = "AdminLast7",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 15, 993, DateTimeKind.Utc).AddTicks(3920),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN7@GMAIL.COM",
                            NormalizedUserName = "ADMIN7",
                            PasswordHash = "AQAAAAIAAYagAAAAEDArfG4Da/lszhbZ/EDfcjhI8jtyn/KwxdVQ8jpCnOSolPIfRn3db1k7EfPtXsUp7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49906a83-ba5d-4737-87fa-5ef4b9e491db",
                            StaffCode = "SD0007",
                            TwoFactorEnabled = false,
                            UserName = "admin7"
                        },
                        new
                        {
                            Id = new Guid("69dece1f-5a5d-43d5-b29b-a8948f9b1ca9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df400006-db2e-435e-8b9b-621b8c716d9a",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 59, DateTimeKind.Utc).AddTicks(9577),
                            DateOfBirth = new DateTime(2006, 2, 15, 11, 30, 16, 59, DateTimeKind.Local).AddTicks(9562),
                            Email = "admin8@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst8",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 59, DateTimeKind.Local).AddTicks(9577),
                            LastName = "AdminLast8",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 59, DateTimeKind.Utc).AddTicks(9585),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN8@GMAIL.COM",
                            NormalizedUserName = "ADMIN8",
                            PasswordHash = "AQAAAAIAAYagAAAAEOnGKa+/72/0ABtzVXihkVnJxlLcNRVojyv5QX7iMnTIeBl74V5CwjN3J8PYC45MLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc5ba411-09e1-4f79-a122-13afb9c592ea",
                            StaffCode = "SD0008",
                            TwoFactorEnabled = false,
                            UserName = "admin8"
                        },
                        new
                        {
                            Id = new Guid("dcd50553-c31f-4d55-ae06-c6cfb8c98101"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da715d47-af23-4186-80ce-42b171b682c8",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 127, DateTimeKind.Utc).AddTicks(9664),
                            DateOfBirth = new DateTime(1998, 7, 4, 11, 30, 16, 127, DateTimeKind.Local).AddTicks(9572),
                            Email = "admin9@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst9",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 127, DateTimeKind.Local).AddTicks(9663),
                            LastName = "AdminLast9",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 127, DateTimeKind.Utc).AddTicks(9664),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN9@GMAIL.COM",
                            NormalizedUserName = "ADMIN9",
                            PasswordHash = "AQAAAAIAAYagAAAAEAcWpGU05Ve9jdgAlnWZMHJvzonnYKFy40o9wPVcCI8FfGXbZ8oVxIkfX8Qefk6n+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "32d859c6-8767-4254-8277-aeb693cf2025",
                            StaffCode = "SD0009",
                            TwoFactorEnabled = false,
                            UserName = "admin9"
                        },
                        new
                        {
                            Id = new Guid("c5408ed6-6101-4b04-8f5b-67d5d57ef7a1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89de65e8-ae67-42d9-ba46-a01c1f6a9780",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 185, DateTimeKind.Utc).AddTicks(6639),
                            DateOfBirth = new DateTime(1999, 11, 10, 11, 30, 16, 185, DateTimeKind.Local).AddTicks(6612),
                            Email = "admin10@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirst10",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 185, DateTimeKind.Local).AddTicks(6638),
                            LastName = "AdminLast10",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 185, DateTimeKind.Utc).AddTicks(6639),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN10@GMAIL.COM",
                            NormalizedUserName = "ADMIN10",
                            PasswordHash = "AQAAAAIAAYagAAAAEGIDjZVrzCcYFej7hrQeOaXtg4X5CKZz7VndinK+Tt6dqc1os0LCh07D3J/xtG6FfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f7d0e9e-33fd-43a6-a885-ab5b435cf901",
                            StaffCode = "SD0010",
                            TwoFactorEnabled = false,
                            UserName = "admin10"
                        },
                        new
                        {
                            Id = new Guid("6f622bb4-3174-4df3-83ad-4f6f0e012517"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "721ba169-924f-49cb-8b71-3f883a3987fc",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 245, DateTimeKind.Utc).AddTicks(1927),
                            DateOfBirth = new DateTime(2006, 1, 2, 11, 30, 16, 245, DateTimeKind.Local).AddTicks(1912),
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst1",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 245, DateTimeKind.Local).AddTicks(1926),
                            LastName = "UserLast1",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 245, DateTimeKind.Utc).AddTicks(1928),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEDj4op6c3W7zbYPepU0KsRCvAZaaUDAwaQ5sKsfjOcu4i5LKKz8dhwgK3TRUjWwn7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b30b851-bf3f-4c72-a105-53dc4a1be280",
                            StaffCode = "SD0011",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("1f99777e-749c-4608-a76b-5b8b07f4c855"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1884ef88-aa4b-4e72-9d14-cffa1778e5fb",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 302, DateTimeKind.Utc).AddTicks(7493),
                            DateOfBirth = new DateTime(1999, 5, 9, 11, 30, 16, 302, DateTimeKind.Local).AddTicks(7480),
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst2",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 302, DateTimeKind.Local).AddTicks(7492),
                            LastName = "UserLast2",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 302, DateTimeKind.Utc).AddTicks(7494),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEBjCEaT//CVFRLaTVpcR7L4eOrBDOyNRE/UVGLfz6hbdfpq7hMC7eRar5+7c0WEckw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7eb1bb0d-da5b-4f3f-923f-84d6fd64ac65",
                            StaffCode = "SD0012",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("13643308-7f88-4caf-a83e-3c7ba53685a0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88b30c9b-f6ca-4aea-ba9d-a6e57639dbe0",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 360, DateTimeKind.Utc).AddTicks(5213),
                            DateOfBirth = new DateTime(2004, 2, 10, 11, 30, 16, 360, DateTimeKind.Local).AddTicks(5199),
                            Email = "user3@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst3",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 360, DateTimeKind.Local).AddTicks(5213),
                            LastName = "UserLast3",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 360, DateTimeKind.Utc).AddTicks(5215),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEKbL5ZWhj2/UYUV84lVZgaUhVwqoPYnBIbJss6F+OUUw1YM/azCVYkDwfPYyH/sTbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bee0ba38-145b-4e96-8596-1980d32ec375",
                            StaffCode = "SD0013",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = new Guid("bcf2971d-119a-4874-a1e7-911c13bf5eb4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d7df455-34a1-4f19-9823-a9d7be5a2c3a",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 418, DateTimeKind.Utc).AddTicks(2277),
                            DateOfBirth = new DateTime(1996, 11, 25, 11, 30, 16, 418, DateTimeKind.Local).AddTicks(2255),
                            Email = "user4@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst4",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 418, DateTimeKind.Local).AddTicks(2276),
                            LastName = "UserLast4",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 418, DateTimeKind.Utc).AddTicks(2278),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER4@GMAIL.COM",
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEMy6jMXLdWxP10XmDzD0phsTHdqz94qZXkZPiumhHhujJI8gsSsIn6hnw848ZUv8xA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aecb0096-53b5-4145-af30-6d01408a197f",
                            StaffCode = "SD0014",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = new Guid("fc4e8cc0-be4a-4540-b4d9-c84ddc307c99"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "084b44b6-8b28-4f55-b099-3a528b3ad8ad",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 476, DateTimeKind.Utc).AddTicks(5567),
                            DateOfBirth = new DateTime(2003, 8, 11, 11, 30, 16, 476, DateTimeKind.Local).AddTicks(5552),
                            Email = "user5@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst5",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 476, DateTimeKind.Local).AddTicks(5566),
                            LastName = "UserLast5",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 476, DateTimeKind.Utc).AddTicks(5568),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER5@GMAIL.COM",
                            NormalizedUserName = "USER5",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXKD9OsaTg0Pt8e9Tuh03ERjMZyAmaPhva1lQpRpDwIdUtI246QsLz54KwAvtmVbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "389ee5f6-e9b9-4e70-843a-80a4feb228a6",
                            StaffCode = "SD0015",
                            TwoFactorEnabled = false,
                            UserName = "user5"
                        },
                        new
                        {
                            Id = new Guid("8fe1fcfe-637f-4102-8d19-bba13343e367"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3211b9ca-05a2-4e96-8989-bea688b73bd1",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 534, DateTimeKind.Utc).AddTicks(3852),
                            DateOfBirth = new DateTime(1995, 2, 25, 11, 30, 16, 534, DateTimeKind.Local).AddTicks(3831),
                            Email = "user6@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst6",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 534, DateTimeKind.Local).AddTicks(3851),
                            LastName = "UserLast6",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 534, DateTimeKind.Utc).AddTicks(3852),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER6@GMAIL.COM",
                            NormalizedUserName = "USER6",
                            PasswordHash = "AQAAAAIAAYagAAAAEOZBwEw7Hutu2AdUNuqWMz3tFtOCQYsdn1xbi+J1DZt0e6/0T9c3kFZNlwzmxPBX/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2f4472fd-5253-4f64-ac80-975a17cec9bc",
                            StaffCode = "SD0016",
                            TwoFactorEnabled = false,
                            UserName = "user6"
                        },
                        new
                        {
                            Id = new Guid("23c25cc5-d6b2-4208-bc8f-a7e153798bbf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10b9aa8d-88e0-4743-be51-2229b6c3a917",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 592, DateTimeKind.Utc).AddTicks(1961),
                            DateOfBirth = new DateTime(1996, 2, 16, 11, 30, 16, 592, DateTimeKind.Local).AddTicks(1951),
                            Email = "user7@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst7",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 592, DateTimeKind.Local).AddTicks(1960),
                            LastName = "UserLast7",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 592, DateTimeKind.Utc).AddTicks(1961),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER7@GMAIL.COM",
                            NormalizedUserName = "USER7",
                            PasswordHash = "AQAAAAIAAYagAAAAEBYqb849VpKCEK3WuccwwkWzlb34PHjqCNyhVaZFj2XgGaPaTnJrR8d3xO00XnkyPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a77772e-30ac-4520-8d02-2d0c5b8f9cc4",
                            StaffCode = "SD0017",
                            TwoFactorEnabled = false,
                            UserName = "user7"
                        },
                        new
                        {
                            Id = new Guid("c0104960-8451-40a9-8331-f0009fb50ee6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cdb84de-70e9-43e8-aec0-d6fa46a178a8",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 650, DateTimeKind.Utc).AddTicks(9068),
                            DateOfBirth = new DateTime(1999, 12, 8, 11, 30, 16, 650, DateTimeKind.Local).AddTicks(9046),
                            Email = "user8@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst8",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 650, DateTimeKind.Local).AddTicks(9067),
                            LastName = "UserLast8",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 650, DateTimeKind.Utc).AddTicks(9068),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER8@GMAIL.COM",
                            NormalizedUserName = "USER8",
                            PasswordHash = "AQAAAAIAAYagAAAAEAjqwIJkmzWPKgbkdPPrnhMIbqDY9wzguXOnkh1mU1EYGhuY21X1DBu0N9nXeq/4ug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0d3376b-8f87-40f4-bc81-9fb3675ce6bc",
                            StaffCode = "SD0018",
                            TwoFactorEnabled = false,
                            UserName = "user8"
                        },
                        new
                        {
                            Id = new Guid("24e0b413-4ccf-41be-ab27-7c18c7678d93"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03f116f8-c8aa-45e8-8cc0-d8bf61cf28f3",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 708, DateTimeKind.Utc).AddTicks(8033),
                            DateOfBirth = new DateTime(2006, 3, 14, 11, 30, 16, 708, DateTimeKind.Local).AddTicks(8019),
                            Email = "user9@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst9",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 708, DateTimeKind.Local).AddTicks(8033),
                            LastName = "UserLast9",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 708, DateTimeKind.Utc).AddTicks(8034),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER9@GMAIL.COM",
                            NormalizedUserName = "USER9",
                            PasswordHash = "AQAAAAIAAYagAAAAEMxPP8xIPf4/d1vFhxL5vhs5UkpH4HZHrcuSX4lRSpPHtYitkeIQnCTIwe0l5uXjPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eae86c89-381a-4dde-b101-f31953dd15d6",
                            StaffCode = "SD0019",
                            TwoFactorEnabled = false,
                            UserName = "user9"
                        },
                        new
                        {
                            Id = new Guid("46247145-edcd-46e8-b0e1-13574884ca6a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "593baea4-a8d0-4b37-8849-373872c4be37",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 769, DateTimeKind.Utc).AddTicks(2458),
                            DateOfBirth = new DateTime(2002, 8, 14, 11, 30, 16, 769, DateTimeKind.Local).AddTicks(2413),
                            Email = "user10@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst10",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 769, DateTimeKind.Local).AddTicks(2457),
                            LastName = "UserLast10",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 769, DateTimeKind.Utc).AddTicks(2458),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER10@GMAIL.COM",
                            NormalizedUserName = "USER10",
                            PasswordHash = "AQAAAAIAAYagAAAAEKIhTLiIPkdCO4f64L8ZecZ6sIhScBrKL0WKtmcsHS3UFK5CB39TD7rlvmpJFQrwzQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b124d587-2d3a-4815-8a53-c5f7027bfc47",
                            StaffCode = "SD0020",
                            TwoFactorEnabled = false,
                            UserName = "user10"
                        },
                        new
                        {
                            Id = new Guid("21058f97-dbbf-479a-a7ce-864fc5121638"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "411f18c2-8cd1-4ce3-8e43-11514f8be67f",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 830, DateTimeKind.Utc).AddTicks(2982),
                            DateOfBirth = new DateTime(2006, 5, 7, 11, 30, 16, 830, DateTimeKind.Local).AddTicks(2969),
                            Email = "user11@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst11",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 830, DateTimeKind.Local).AddTicks(2982),
                            LastName = "UserLast11",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 830, DateTimeKind.Utc).AddTicks(2983),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER11@GMAIL.COM",
                            NormalizedUserName = "USER11",
                            PasswordHash = "AQAAAAIAAYagAAAAEE430QghphE6agzMQfgDgPc9jCEe73QT9qMtDpTp+QXAKv46JISlIr+ObfKhAy2KZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25a6bdb1-5a12-4d0b-bb2d-c3a7152d3d7d",
                            StaffCode = "SD0021",
                            TwoFactorEnabled = false,
                            UserName = "user11"
                        },
                        new
                        {
                            Id = new Guid("2e7c830c-aff0-4f7f-93a2-627b45f23371"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af161bc5-9de0-4e65-b730-601a0678f844",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 891, DateTimeKind.Utc).AddTicks(4780),
                            DateOfBirth = new DateTime(2004, 9, 24, 11, 30, 16, 891, DateTimeKind.Local).AddTicks(4757),
                            Email = "user12@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst12",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 891, DateTimeKind.Local).AddTicks(4779),
                            LastName = "UserLast12",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 891, DateTimeKind.Utc).AddTicks(4780),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER12@GMAIL.COM",
                            NormalizedUserName = "USER12",
                            PasswordHash = "AQAAAAIAAYagAAAAEDxleJxozhVN+ZY2xkDMGKc5wBehakuxX8RdL+BrtaQWERUJDvz1gHSxRwcIt60R9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a481b6f2-17d5-402d-9d5b-5334f0b76879",
                            StaffCode = "SD0022",
                            TwoFactorEnabled = false,
                            UserName = "user12"
                        },
                        new
                        {
                            Id = new Guid("a0250c52-87ef-418d-b625-515c3bc0a6bd"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a9b96a1-d999-4e98-8a39-a6c022f2ac6c",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 949, DateTimeKind.Utc).AddTicks(3919),
                            DateOfBirth = new DateTime(2000, 5, 6, 11, 30, 16, 949, DateTimeKind.Local).AddTicks(3904),
                            Email = "user13@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst13",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 16, 949, DateTimeKind.Local).AddTicks(3918),
                            LastName = "UserLast13",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 16, 949, DateTimeKind.Utc).AddTicks(3920),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER13@GMAIL.COM",
                            NormalizedUserName = "USER13",
                            PasswordHash = "AQAAAAIAAYagAAAAECbf6oL7Bi58T1DlRRQl2IgPYvGgA66Wl1c/oYnO9bCAcQsDUFUHsHJDycfOu83c6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "627c96ff-26bb-442f-bf4b-5710792e0226",
                            StaffCode = "SD0023",
                            TwoFactorEnabled = false,
                            UserName = "user13"
                        },
                        new
                        {
                            Id = new Guid("87badc17-7c6a-4caf-b58c-1713fb091128"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbed96b5-8ce4-469e-a036-f7cc6462825c",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 7, DateTimeKind.Utc).AddTicks(1112),
                            DateOfBirth = new DateTime(2002, 1, 14, 11, 30, 17, 7, DateTimeKind.Local).AddTicks(1101),
                            Email = "user14@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst14",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 7, DateTimeKind.Local).AddTicks(1111),
                            LastName = "UserLast14",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 7, DateTimeKind.Utc).AddTicks(1112),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER14@GMAIL.COM",
                            NormalizedUserName = "USER14",
                            PasswordHash = "AQAAAAIAAYagAAAAEEwDbMKfWyolyfhEnJ6zUf/dg2Npn1QiUmH2XvaqV7LgiYuqIbkI16b5ozTx4EQOqA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "267a185f-f7ab-4c3d-946a-b23a841fbfbf",
                            StaffCode = "SD0024",
                            TwoFactorEnabled = false,
                            UserName = "user14"
                        },
                        new
                        {
                            Id = new Guid("61385cbf-0859-4731-95bf-0bf1d95425e2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9c3827e-ce78-4141-8317-dab0715d9c54",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 66, DateTimeKind.Utc).AddTicks(5226),
                            DateOfBirth = new DateTime(1998, 8, 9, 11, 30, 17, 66, DateTimeKind.Local).AddTicks(5211),
                            Email = "user15@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst15",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 66, DateTimeKind.Local).AddTicks(5225),
                            LastName = "UserLast15",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 66, DateTimeKind.Utc).AddTicks(5227),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER15@GMAIL.COM",
                            NormalizedUserName = "USER15",
                            PasswordHash = "AQAAAAIAAYagAAAAELkbll6e6EcUIRLOdkgRdhIXvlxhzC7qq6ei+dysf8sfebYheDnL7Q910KSN/ODh+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7233675-431c-4969-84d0-d4942db93737",
                            StaffCode = "SD0025",
                            TwoFactorEnabled = false,
                            UserName = "user15"
                        },
                        new
                        {
                            Id = new Guid("9f1f22e3-c832-46cf-8313-b814475bc0be"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1402e816-c66d-4fa3-9a8d-f4144e1b0f88",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 124, DateTimeKind.Utc).AddTicks(4013),
                            DateOfBirth = new DateTime(1998, 3, 25, 11, 30, 17, 124, DateTimeKind.Local).AddTicks(3997),
                            Email = "user16@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst16",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 124, DateTimeKind.Local).AddTicks(4013),
                            LastName = "UserLast16",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 124, DateTimeKind.Utc).AddTicks(4014),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER16@GMAIL.COM",
                            NormalizedUserName = "USER16",
                            PasswordHash = "AQAAAAIAAYagAAAAEMnQCjlDqVxTrH1yGf0YfGlzMB+aOyMIf1gZ6OoLEZaFYRftSybX7GpsTcx/PafFGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb752752-38a1-42ed-b1df-416d68917147",
                            StaffCode = "SD0026",
                            TwoFactorEnabled = false,
                            UserName = "user16"
                        },
                        new
                        {
                            Id = new Guid("49b0e3de-468e-4e65-96b9-ef9f2b3a7a9d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3ba18bf-3d2e-4e19-8f25-c2105ebfc1cf",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 183, DateTimeKind.Utc).AddTicks(981),
                            DateOfBirth = new DateTime(2000, 11, 11, 11, 30, 17, 183, DateTimeKind.Local).AddTicks(912),
                            Email = "user17@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst17",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 183, DateTimeKind.Local).AddTicks(980),
                            LastName = "UserLast17",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 183, DateTimeKind.Utc).AddTicks(981),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER17@GMAIL.COM",
                            NormalizedUserName = "USER17",
                            PasswordHash = "AQAAAAIAAYagAAAAEDQE/3OdVJeZeyOo+HCH17V2+Ruuxz/Q8v4MlRhepZPBjWBdPmXFwTz2UVdUeCtN1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac4b7248-5b42-4695-8bd4-83608eefd1c8",
                            StaffCode = "SD0027",
                            TwoFactorEnabled = false,
                            UserName = "user17"
                        },
                        new
                        {
                            Id = new Guid("cc898763-41d5-48f1-ac48-693d57837125"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6da2d6db-40cd-4f47-8bf4-cc3b930bcd51",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 241, DateTimeKind.Utc).AddTicks(1015),
                            DateOfBirth = new DateTime(2006, 3, 30, 11, 30, 17, 241, DateTimeKind.Local).AddTicks(999),
                            Email = "user18@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst18",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 241, DateTimeKind.Local).AddTicks(1014),
                            LastName = "UserLast18",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 241, DateTimeKind.Utc).AddTicks(1016),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER18@GMAIL.COM",
                            NormalizedUserName = "USER18",
                            PasswordHash = "AQAAAAIAAYagAAAAEKWTDX2/6/wNDpQowyuRij52O6HhskOtifIw/zkBL8Hz6jQ0IwpwdDYClcqq4EtlBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49d505a2-4f7b-4dfd-a466-abcee928c3d4",
                            StaffCode = "SD0028",
                            TwoFactorEnabled = false,
                            UserName = "user18"
                        },
                        new
                        {
                            Id = new Guid("af1763bc-7bee-4d7d-aa72-d05ede7df398"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9245dd5d-6dd1-4358-a7b4-b79dc84cf98e",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 299, DateTimeKind.Utc).AddTicks(6464),
                            DateOfBirth = new DateTime(2006, 1, 15, 11, 30, 17, 299, DateTimeKind.Local).AddTicks(6445),
                            Email = "user19@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst19",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 299, DateTimeKind.Local).AddTicks(6463),
                            LastName = "UserLast19",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 299, DateTimeKind.Utc).AddTicks(6464),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER19@GMAIL.COM",
                            NormalizedUserName = "USER19",
                            PasswordHash = "AQAAAAIAAYagAAAAEHztvIQupEhQXL33EuzNoIE7tEgkiy+wNJ7fXTrenCL1L1H2nUxCtLcMtcA3J0pXxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35fcdcdc-654b-4987-9ef7-4535755c9b57",
                            StaffCode = "SD0029",
                            TwoFactorEnabled = false,
                            UserName = "user19"
                        },
                        new
                        {
                            Id = new Guid("3bb4080b-c5f2-41af-8111-05173653de3d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9ed6dd2-9730-4a45-868e-a7dffb31396b",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 357, DateTimeKind.Utc).AddTicks(5794),
                            DateOfBirth = new DateTime(2006, 4, 3, 11, 30, 17, 357, DateTimeKind.Local).AddTicks(5779),
                            Email = "user20@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst20",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 357, DateTimeKind.Local).AddTicks(5793),
                            LastName = "UserLast20",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 357, DateTimeKind.Utc).AddTicks(5794),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER20@GMAIL.COM",
                            NormalizedUserName = "USER20",
                            PasswordHash = "AQAAAAIAAYagAAAAEP8Mk9mixKSJP3GpIC+RTddNh436Y8VO9Mh8yk5plq4t2iwyo6/RnGnsEiM13dLvNQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64d3d6d1-c041-4dc6-8d21-1a207f88d4df",
                            StaffCode = "SD0030",
                            TwoFactorEnabled = false,
                            UserName = "user20"
                        },
                        new
                        {
                            Id = new Guid("073f88cc-3f6d-48e6-bdca-4c3f972ffcfd"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c545f7cd-4ab9-4ba4-9350-c38badf6a8a4",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 415, DateTimeKind.Utc).AddTicks(7804),
                            DateOfBirth = new DateTime(1997, 5, 27, 11, 30, 17, 415, DateTimeKind.Local).AddTicks(7786),
                            Email = "user21@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst21",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 415, DateTimeKind.Local).AddTicks(7804),
                            LastName = "UserLast21",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 415, DateTimeKind.Utc).AddTicks(7805),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER21@GMAIL.COM",
                            NormalizedUserName = "USER21",
                            PasswordHash = "AQAAAAIAAYagAAAAEIMyiGKFbqO9+sPJdYQNQqGxKtDU8enXar0CxQ6LIqYHFR+nK050DJRrd/7wFixT2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "87f3c29e-4921-4e5d-9297-4fe6b8a196b3",
                            StaffCode = "SD0031",
                            TwoFactorEnabled = false,
                            UserName = "user21"
                        },
                        new
                        {
                            Id = new Guid("d4dd55be-9b27-4af1-8b55-4edb19be88a9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca297246-db16-4198-8ded-f24c25e82a3b",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 474, DateTimeKind.Utc).AddTicks(6564),
                            DateOfBirth = new DateTime(2004, 3, 25, 11, 30, 17, 474, DateTimeKind.Local).AddTicks(6551),
                            Email = "user22@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst22",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 474, DateTimeKind.Local).AddTicks(6562),
                            LastName = "UserLast22",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 474, DateTimeKind.Utc).AddTicks(6565),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER22@GMAIL.COM",
                            NormalizedUserName = "USER22",
                            PasswordHash = "AQAAAAIAAYagAAAAEDaY1zNI093rIIg/8Is3frVYiQR46Y2NMszscFLFlGcPHiRJZt0jOSvyMAjQXnp8NQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "310ed73f-ba2a-423a-ad67-e915b4614650",
                            StaffCode = "SD0032",
                            TwoFactorEnabled = false,
                            UserName = "user22"
                        },
                        new
                        {
                            Id = new Guid("cf3d6527-4bb9-4329-ba81-ee2ee488debc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5192d79-6074-4729-8ab3-e89d8fd55b4f",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 533, DateTimeKind.Utc).AddTicks(6655),
                            DateOfBirth = new DateTime(1997, 3, 30, 11, 30, 17, 533, DateTimeKind.Local).AddTicks(6632),
                            Email = "user23@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst23",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 533, DateTimeKind.Local).AddTicks(6653),
                            LastName = "UserLast23",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 533, DateTimeKind.Utc).AddTicks(6656),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER23@GMAIL.COM",
                            NormalizedUserName = "USER23",
                            PasswordHash = "AQAAAAIAAYagAAAAEG3AqGkR6/i3OkIprmktyUWncP5C0opmcLSy7aerBH3fwKh8wMSM39QgeOBDtAU+nA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c66c888-73b1-4bec-b858-87637b5d3a3f",
                            StaffCode = "SD0033",
                            TwoFactorEnabled = false,
                            UserName = "user23"
                        },
                        new
                        {
                            Id = new Guid("30b3d356-fb3f-4957-ab96-bfb83153c289"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a5e1747-c50f-4660-8302-5f55410e6954",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 592, DateTimeKind.Utc).AddTicks(9720),
                            DateOfBirth = new DateTime(1995, 10, 3, 11, 30, 17, 592, DateTimeKind.Local).AddTicks(9707),
                            Email = "user24@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst24",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 592, DateTimeKind.Local).AddTicks(9719),
                            LastName = "UserLast24",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 592, DateTimeKind.Utc).AddTicks(9721),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER24@GMAIL.COM",
                            NormalizedUserName = "USER24",
                            PasswordHash = "AQAAAAIAAYagAAAAEJMHdvC6x7zYcQLhgRkHQcj5ltrR75DVVna60Vjgx7Mnds8v0Q+O+KCw8Yyag1f/8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "67f47baf-3c6b-4a6f-b340-341aa76046b9",
                            StaffCode = "SD0034",
                            TwoFactorEnabled = false,
                            UserName = "user24"
                        },
                        new
                        {
                            Id = new Guid("a4fba5a1-0e66-41be-bc1a-a6c1049065cb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0a1c790-9baa-4828-b689-6546f23adcae",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 651, DateTimeKind.Utc).AddTicks(8804),
                            DateOfBirth = new DateTime(2004, 11, 14, 11, 30, 17, 651, DateTimeKind.Local).AddTicks(8795),
                            Email = "user25@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst25",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 651, DateTimeKind.Local).AddTicks(8803),
                            LastName = "UserLast25",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 651, DateTimeKind.Utc).AddTicks(8805),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER25@GMAIL.COM",
                            NormalizedUserName = "USER25",
                            PasswordHash = "AQAAAAIAAYagAAAAEPOw4/DgY0jkCzlgmY8KSAGCDXGmrmp0TJR5vQ+13ydgorLYXaa/mnWdzVrVqWUMWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9a0d0f55-365e-4f26-9a2f-4cd60aadef87",
                            StaffCode = "SD0035",
                            TwoFactorEnabled = false,
                            UserName = "user25"
                        },
                        new
                        {
                            Id = new Guid("aa37189b-926e-4bb8-ae78-5e41e8a16964"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4d808e6-900c-483a-93f2-5b59b5dd3bd1",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 711, DateTimeKind.Utc).AddTicks(6509),
                            DateOfBirth = new DateTime(1999, 11, 9, 11, 30, 17, 711, DateTimeKind.Local).AddTicks(6494),
                            Email = "user26@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst26",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 711, DateTimeKind.Local).AddTicks(6508),
                            LastName = "UserLast26",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 711, DateTimeKind.Utc).AddTicks(6510),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER26@GMAIL.COM",
                            NormalizedUserName = "USER26",
                            PasswordHash = "AQAAAAIAAYagAAAAENjOCEFi5r7tfLuAWHXURrv6lbSwrVP1/T0vBqhnTVZQ1bKuQlGg3mClvftx/h48Zw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc6e5f56-b670-47cb-86d3-74df81798159",
                            StaffCode = "SD0036",
                            TwoFactorEnabled = false,
                            UserName = "user26"
                        },
                        new
                        {
                            Id = new Guid("1f62e3ba-7b67-4bb5-9990-8ae88fe7412f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "444a2154-5299-4a77-b493-30b7f7e24551",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 770, DateTimeKind.Utc).AddTicks(5572),
                            DateOfBirth = new DateTime(1998, 10, 5, 11, 30, 17, 770, DateTimeKind.Local).AddTicks(5556),
                            Email = "user27@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst27",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 770, DateTimeKind.Local).AddTicks(5571),
                            LastName = "UserLast27",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 770, DateTimeKind.Utc).AddTicks(5573),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER27@GMAIL.COM",
                            NormalizedUserName = "USER27",
                            PasswordHash = "AQAAAAIAAYagAAAAEOJqsPKNHJu/ckB8E48vceHTXUM8Fi8PKopKhWHEQqlTYNDJ17/w0JKWUadUAH5q5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6add2081-d372-44d3-a52e-24b6257568ce",
                            StaffCode = "SD0037",
                            TwoFactorEnabled = false,
                            UserName = "user27"
                        },
                        new
                        {
                            Id = new Guid("e8cd88d7-cdd5-4dd5-8fdf-bc184450ec7b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d25d4794-8c92-4400-88c8-58abdd504cfc",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 829, DateTimeKind.Utc).AddTicks(7118),
                            DateOfBirth = new DateTime(2003, 12, 21, 11, 30, 17, 829, DateTimeKind.Local).AddTicks(7102),
                            Email = "user28@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst28",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 829, DateTimeKind.Local).AddTicks(7113),
                            LastName = "UserLast28",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 829, DateTimeKind.Utc).AddTicks(7119),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER28@GMAIL.COM",
                            NormalizedUserName = "USER28",
                            PasswordHash = "AQAAAAIAAYagAAAAEMeJf85V03vSPtCQ5FptYHFswgkI+gfto9grwRptJTeut3whnILg/uLwFmIDDXx7+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a2dcfff-165b-412b-a06d-d9aad61a1d54",
                            StaffCode = "SD0038",
                            TwoFactorEnabled = false,
                            UserName = "user28"
                        },
                        new
                        {
                            Id = new Guid("25b9a0d1-1b61-4597-b9b7-42ed331d6498"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f222f3c-3912-46e9-8b0f-4578448109ed",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 888, DateTimeKind.Utc).AddTicks(4868),
                            DateOfBirth = new DateTime(1994, 10, 9, 11, 30, 17, 888, DateTimeKind.Local).AddTicks(4859),
                            Email = "user29@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst29",
                            Gender = "Female",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 888, DateTimeKind.Local).AddTicks(4868),
                            LastName = "UserLast29",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 888, DateTimeKind.Utc).AddTicks(4869),
                            Location = "HCM",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER29@GMAIL.COM",
                            NormalizedUserName = "USER29",
                            PasswordHash = "AQAAAAIAAYagAAAAEGnYTfDbdqFRjBjCqg7hwRU4+xYn8WfT/a3vuAV3CItMy548KIFfaHiYNfECuBRHVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e10b253-b42a-41fe-8ef7-84cd7cf362cc",
                            StaffCode = "SD0039",
                            TwoFactorEnabled = false,
                            UserName = "user29"
                        },
                        new
                        {
                            Id = new Guid("0a365594-90f6-4e14-a2bb-6a267c62f1af"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da4cbe89-d90f-4990-af71-98a10019bf10",
                            CreatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 947, DateTimeKind.Utc).AddTicks(5154),
                            DateOfBirth = new DateTime(2005, 2, 2, 11, 30, 17, 947, DateTimeKind.Local).AddTicks(5140),
                            Email = "user30@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "UserFirst30",
                            Gender = "Male",
                            IsDisabled = false,
                            IsPasswordChanged = true,
                            JoinedDate = new DateTime(2024, 6, 21, 11, 30, 17, 947, DateTimeKind.Local).AddTicks(5153),
                            LastName = "UserLast30",
                            LastUpdatedDateTime = new DateTime(2024, 6, 21, 4, 30, 17, 947, DateTimeKind.Utc).AddTicks(5155),
                            Location = "HN",
                            LockoutEnabled = true,
                            NormalizedEmail = "USER30@GMAIL.COM",
                            NormalizedUserName = "USER30",
                            PasswordHash = "AQAAAAIAAYagAAAAEN/kMI6bCJqf3rCynUksdlIBekZv5jVT4wf9WjIyPRgH7DzJwFku5YpznfO/0FrLmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b709ed66-16c7-4edd-96aa-0992f7fc8f51",
                            StaffCode = "SD0040",
                            TwoFactorEnabled = false,
                            UserName = "user30"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3"),
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("fe4d7e10-e60c-445a-8c6c-a00edc97e42f"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("bafc9d75-79bd-4608-abca-7e9931a0d7d4"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("ad9c337a-bb6b-4949-b796-14620afd0f08"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("94814fe8-b396-4bb5-9f64-e9d91407c831"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("523b214c-6eac-42f1-96b2-cc1fca0ad2ec"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("e11eb642-3086-4b6f-9ef0-d10460968dd5"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("69dece1f-5a5d-43d5-b29b-a8948f9b1ca9"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("dcd50553-c31f-4d55-ae06-c6cfb8c98101"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("c5408ed6-6101-4b04-8f5b-67d5d57ef7a1"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("6f622bb4-3174-4df3-83ad-4f6f0e012517"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("1f99777e-749c-4608-a76b-5b8b07f4c855"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("13643308-7f88-4caf-a83e-3c7ba53685a0"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("bcf2971d-119a-4874-a1e7-911c13bf5eb4"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("fc4e8cc0-be4a-4540-b4d9-c84ddc307c99"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("8fe1fcfe-637f-4102-8d19-bba13343e367"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("23c25cc5-d6b2-4208-bc8f-a7e153798bbf"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("c0104960-8451-40a9-8331-f0009fb50ee6"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("24e0b413-4ccf-41be-ab27-7c18c7678d93"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("46247145-edcd-46e8-b0e1-13574884ca6a"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("21058f97-dbbf-479a-a7ce-864fc5121638"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("2e7c830c-aff0-4f7f-93a2-627b45f23371"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("a0250c52-87ef-418d-b625-515c3bc0a6bd"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("87badc17-7c6a-4caf-b58c-1713fb091128"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("61385cbf-0859-4731-95bf-0bf1d95425e2"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("9f1f22e3-c832-46cf-8313-b814475bc0be"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("49b0e3de-468e-4e65-96b9-ef9f2b3a7a9d"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("cc898763-41d5-48f1-ac48-693d57837125"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("af1763bc-7bee-4d7d-aa72-d05ede7df398"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("3bb4080b-c5f2-41af-8111-05173653de3d"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("073f88cc-3f6d-48e6-bdca-4c3f972ffcfd"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("d4dd55be-9b27-4af1-8b55-4edb19be88a9"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("cf3d6527-4bb9-4329-ba81-ee2ee488debc"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("30b3d356-fb3f-4957-ab96-bfb83153c289"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("a4fba5a1-0e66-41be-bc1a-a6c1049065cb"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("aa37189b-926e-4bb8-ae78-5e41e8a16964"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("1f62e3ba-7b67-4bb5-9990-8ae88fe7412f"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("e8cd88d7-cdd5-4dd5-8fdf-bc184450ec7b"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("25b9a0d1-1b61-4597-b9b7-42ed331d6498"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("0a365594-90f6-4e14-a2bb-6a267c62f1af"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
